"""
recommender.py
==============
Core recommender pipeline for the HDB Flat Finder Streamlit app.

No live API calls at runtime. Walking times are pre-loaded from:
    data/listings_with_walking_times.csv
(generated by backend/preload_walking_times.py)

Scoring formula
---------------
    amenity_score = Σ  scoring_weights[a] × avg_exp_decay(walk_times[a], TAU)
    value_score   = normalise(value_delta_pct, clip=±10%) → 0..1
    final_score   = α × amenity_score + (1−α) × value_score

    where scoring_weights come from rank_sum_weights(final_ranking)
    and final_ranking is the confirmed output of the quiz in quiz.py.

Usage
-----
    import streamlit as st
    from backend.recommender import load_listings, run_recommender

    @st.cache_data
    def get_listings():
        return load_listings()

    listings_df = get_listings()

    results = run_recommender(
        listings_df     = listings_df,
        amenity_ranking = final_ranking,    # from render_quiz()
        amenity_weights = scoring_weights,  # from render_quiz()
        alpha           = 0.75,
        budget          = 700_000,
        rooms           = [3, 4],
        preferred_towns = ["TAMPINES"],
        min_sqft        = 0,
    )

    top10 = results["top"]       # DataFrame, scrambled, ready for Tinder swipe
    n     = results["n_filtered"] # int, how many passed hard filters
"""

import math
import random
import logging
from pathlib import Path

import numpy as np
import pandas as pd
from backend.utils.constants import AMENITY_MAPPING


log = logging.getLogger(__name__)

# ── Config ─────────────────────────────────────────────────────────────────────
DATA_DIR      = Path("backend_predictor_listings/price_predictor/csv_outputs")
LISTINGS_PATH = DATA_DIR / "listings_with_walking_times_full.csv"

TAU_WALKING = 8.0    # minutes — exp(-t/TAU); score ≈ 0.37 at 8 min walk
VALUE_CLIP  = 0.10   # clip value_delta_pct to ±10% before normalising
TOP_N       = 10     # listings returned for Tinder swipe


RANKING_ALPHA = {
    "amenity-first": 0.75,
    "balanced": 0.50,
    "value-first": 0.25,
}

# ── Data loading ───────────────────────────────────────────────────────────────


def load_listings(path: Path = LISTINGS_PATH) -> pd.DataFrame:
    """
    Load the pre-processed listings CSV (output of preload_walking_times.py).
    Wrap with @st.cache_data so it only loads once per Streamlit session.

    Raises FileNotFoundError with a helpful message if the file is missing.
    """
    if not path.exists():
        raise FileNotFoundError(
            f"Listings file not found: {path}\n"
            "Run backend/preload_walking_times.py first to generate it, "
            "or check that data/ is in the right place relative to your app."
        )
    df = pd.read_csv(path)
    log.info(f"Loaded {len(df)} listings from {path}")
    return df


# ── Math helpers ───────────────────────────────────────────────────────────────

def _avg_exp_decay(times: list, tau: float) -> float:
    """
    mean(exp(-t / tau)) over a list of walking times in minutes.
    Skips None and NaN. Returns 0.0 if no valid values.
    """
    valid = [
        t for t in times
        if t is not None and not (isinstance(t, float) and math.isnan(t))
    ]
    if not valid:
        return 0.0
    return float(np.mean([math.exp(-t / tau) for t in valid]))


def _amenity_score(
    listing: pd.Series,
    amenity_ranking: list[str],
    scoring_weights: dict[str, float],
    tau: float = TAU_WALKING,
) -> tuple[float, dict[str, float]]:
    per_acc = {}

    for amenity in amenity_ranking:
        col_key = AMENITY_MAPPING.get(amenity)
        if col_key is None:
            per_acc[amenity] = 0.0
            continue

        times = [
            listing.get(f"walk_{col_key}_min1"),
            listing.get(f"walk_{col_key}_min2"),
            listing.get(f"walk_{col_key}_min3"),
        ]

        times = [
            t for t in times
            if pd.notna(t)
        ]

        if not times:
            avg = listing.get(f"walk_{col_key}_avg_mins")
            if pd.notna(avg):
                times = [avg]

        per_acc[amenity] = _avg_exp_decay(times, tau)

    score = sum(
        scoring_weights.get(a, 0.0) * per_acc.get(a, 0.0)
        for a in amenity_ranking
    )

    return round(score, 4), {a: round(v, 4) for a, v in per_acc.items()}


def _value_score(value_delta_pct: float, clip: float = VALUE_CLIP) -> float:
    """
    Normalise value_delta_pct → 0..1.

    value_delta_pct = (predicted − asking) / predicted × 100
        positive → predicted > asking → undervalued → higher score
        negative → predicted < asking → overvalued  → lower score

    Clipped to ±clip before normalising.
    """
    pct     = value_delta_pct / 100.0
    clipped = float(np.clip(pct, -clip, clip))
    return round((clipped + clip) / (2 * clip), 4)


# ── Stage 1: Hard filter ───────────────────────────────────────────────────────

def stage1_filter(
    listings_df:     pd.DataFrame,
    budget:          int,
    rooms:           list[int],
    preferred_towns: list[str],
    min_sqft:        int = 0,
) -> pd.DataFrame:
    """
    Filter listings by hard constraints.

    Parameters
    ----------
    listings_df     : full listings DataFrame from load_listings()
    budget          : max asking_price in SGD
    rooms           : acceptable bedroom counts e.g. [3, 4]; [] = any
    preferred_towns : town strings e.g. ["TAMPINES"]; [] = any
    min_sqft        : minimum floor_area_sqft; 0 = no minimum

    Returns
    -------
    Filtered DataFrame with index reset.
    """
    df = listings_df.copy()
    df = df[df["asking_price"] <= budget]
    if min_sqft > 0:
        min_sqm = min_sqft / 10.7639
        df = df[df["floor_area_sqm"] >= min_sqm]
    if rooms:
        allowed_flat_types = [f"{r} ROOM" for r in rooms]
        df = df[df["flat_type"].isin(allowed_flat_types)]
    if preferred_towns:
        towns_upper = [t.upper().strip() for t in preferred_towns]
        df = df[df["town"].str.upper().isin(towns_upper)]
    return df.reset_index(drop=True)


# ── Stage 3: Score and rank ────────────────────────────────────────────────────

def stage3_score(
    filtered_df:     pd.DataFrame,
    amenity_ranking: list[str],
    scoring_weights: dict[str, float],
    alpha:           float,
    top_n:           int = TOP_N,
) -> pd.DataFrame:
    """
    Score all filtered listings and return top_n by final_score.

    final_score = alpha × amenity_score + (1 − alpha) × value_score

    Parameters
    ----------
    filtered_df     : output of stage1_filter()
    amenity_ranking : ordered amenity keys from quiz, most important first
    scoring_weights : rank-sum weights from rank_sum_weights(final_ranking)
    alpha           : 0..1 — 1.0 = pure amenity, 0.0 = pure value
    top_n           : how many listings to return

    Returns
    -------
    DataFrame sorted by final_score descending, limited to top_n.
    Columns:
        address, town, bedrooms, floor_area_sqft,
        asking_price, predicted_price, value_delta_pct,
        latitude, longitude,
        amenity_score, value_score, final_score,
        walk_acc_{amenity}      — exp-decay accessibility score 0..1
        walk_{amenity}_avg_mins — average walking time in minutes (for display)
    """
    records = []
    for _, listing in filtered_df.iterrows():
        a_score, per_acc = _amenity_score(listing, amenity_ranking, scoring_weights)
        v_score          = _value_score(-listing.get("valuation_pct", 0))
        f_score          = round(alpha * a_score + (1 - alpha) * v_score, 4)

        record = {
            "listing_id":      listing.get("listing_id"),
            "address":         listing.get("full_address", ""),
            "town":            listing.get("town", ""),
            "flat_type":        listing.get("flat_type", ""),
            "floor_area_sqm": listing.get("floor_area_sqm", ""),
            "asking_price":    listing.get("asking_price", 0),
            "predicted_price": listing.get("predicted_price", None),
            "valuation_pct": listing.get("valuation_pct", 0),
            "lat":        listing.get("lat"),
            "lon":       listing.get("lon"),
            "amenity_score":   a_score,
            "value_score":     v_score,
            "final_score":     f_score,
            "storey_range": listing.get("storey_range"),
            "storey_midpoint": listing.get("storey_midpoint"),
            "remaining_lease": listing.get("remaining_lease"),
            "remaining_lease_years": listing.get("remaining_lease_years"),
            "train_1_dist_m": listing.get("train_1_dist_m"),
            "bus_1_dist_m": listing.get("bus_1_dist_m"),
            "school_1_dist_m": listing.get("school_1_dist_m"),
            "hawker_1_dist_m": listing.get("hawker_1_dist_m"),
            "mall_1_dist_m": listing.get("mall_1_dist_m"),
            "polyclinic_1_dist_m": listing.get("polyclinic_1_dist_m"),
            "supermarket_1_dist_m": listing.get("supermarket_1_dist_m"),

            "walk_train_min1": listing.get("walk_train_min1"),
            "walk_bus_min1": listing.get("walk_bus_min1"),
            "walk_primary_school_min1": listing.get("walk_primary_school_min1"),
            "walk_hawker_min1": listing.get("walk_hawker_min1"),
            "walk_mall_min1": listing.get("walk_mall_min1"),
            "walk_polyclinic_min1": listing.get("walk_polyclinic_min1"),
            "walk_supermarket_min1": listing.get("walk_supermarket_min1"),
        }
        for a in amenity_ranking:
            col_key = AMENITY_MAPPING.get(a)
            record[f"walk_acc_{a}"] = per_acc.get(a, 0.0)
            record[f"walk_{a}_avg_mins"] = listing.get(f"walk_{col_key}_avg_mins") if col_key else None
        records.append(record)

    if not records:
        return pd.DataFrame()

    return (
        pd.DataFrame(records)
        .sort_values("final_score", ascending=False)
        .reset_index(drop=True)
        .head(top_n)
    )


# ── Main entry point ───────────────────────────────────────────────────────────

def run_recommender(
    listings_df:     pd.DataFrame,
    amenity_ranking: list[str],
    amenity_weights: dict[str, float],
    alpha:           float,
    budget:          int,
    rooms:           list[int],
    preferred_towns: list[str] = None,
    min_sqft:        int       = 0,
    top_n:           int       = TOP_N,
) -> dict:
    """
    Full recommender pipeline.

    Parameters
    ----------
    listings_df     : output of load_listings()
    amenity_ranking : ordered amenity keys — final_ranking from render_quiz()
    amenity_weights : rank-sum weights    — scoring_weights from render_quiz()
    alpha           : float 0..1 from slider (1.0 = pure amenity, 0.0 = pure value)
    budget          : max asking_price SGD
    rooms           : acceptable bedroom counts; [] = any
    preferred_towns : town strings; [] = any
    min_sqft        : minimum sqft; 0 = no minimum
    top_n           : listings for Tinder swipe (default 10)

    Returns
    -------
    {
        "filtered"   : DataFrame after Stage 1 hard filter
        "top"        : DataFrame of top top_n listings, SCRAMBLED (scores hidden)
        "weights"    : amenity_weights used for scoring
        "n_filtered" : int — listings that passed hard filter
    }
    """
    # Stage 1 — hard filter
    filtered = stage1_filter(
        listings_df     = listings_df,
        budget          = budget,
        rooms           = rooms,
        preferred_towns = preferred_towns or [],
        min_sqft        = min_sqft,
    )

    if filtered.empty:
        return {
            "filtered":   filtered,
            "top":        pd.DataFrame(),
            "weights":    amenity_weights,
            "n_filtered": 0,
        }

    # Stage 3 — score + rank
    top = stage3_score(
        filtered_df     = filtered,
        amenity_ranking = amenity_ranking,
        scoring_weights = amenity_weights,
        alpha           = alpha,
        top_n           = top_n,
    )

    # Scramble — hide scoring signal for Tinder swipe UI
    top_scrambled = (
        top.sample(frac=1, random_state=random.randint(0, 9999))
           .reset_index(drop=True)
    )

    return {
        "filtered":   filtered,
        "top":        top_scrambled,
        "weights":    amenity_weights,
        "n_filtered": len(filtered),
    }
